{
  description = ''Autogenerated glew bindings for Nim'';
    inputs.flakeNimbleLib.type = "github";
  inputs.flakeNimbleLib.owner = "riinr";
  inputs.flakeNimbleLib.repo = "flake-nimble";
  inputs.flakeNimbleLib.ref = "flake-pinning";
  inputs.flakeNimbleLib.dir = "nimpkgs/";
  inputs.src-glew-master.flake = false;
  inputs.src-glew-master.type = "github";
  inputs.src-glew-master.owner = "jyapayne";
  inputs.src-glew-master.repo = "nim-glew";
  inputs.src-glew-master.ref = "refs/heads/master";
  
  
  inputs."https://github.com/jyapayne/nimterop".type = "github";
  inputs."https://github.com/jyapayne/nimterop".owner = "riinr";
  inputs."https://github.com/jyapayne/nimterop".repo = "flake-nimble";
  inputs."https://github.com/jyapayne/nimterop".ref = "flake-pinning";
  inputs."https://github.com/jyapayne/nimterop".dir = "nimpkgs/h/https://github.com/jyapayne/nimterop";

  
  inputs."https://github.com/jyapayne/nim-glfw".type = "github";
  inputs."https://github.com/jyapayne/nim-glfw".owner = "riinr";
  inputs."https://github.com/jyapayne/nim-glfw".repo = "flake-nimble";
  inputs."https://github.com/jyapayne/nim-glfw".ref = "flake-pinning";
  inputs."https://github.com/jyapayne/nim-glfw".dir = "nimpkgs/h/https://github.com/jyapayne/nim-glfw";

  outputs = { self, nixpkgs, flakeNimbleLib, src-glew-master, ...}@deps:
    let lib = flakeNimbleLib.lib;
    in lib.mkRefOutput {
      inherit self nixpkgs ;
      src = src-glew-master;
      deps = builtins.removeAttrs deps ["self" "nixpkgs" "flakeNimbleLib" "src-glew-master"];
      meta = builtins.fromJSON (builtins.readFile ./meta.json);
    };
}