{
  description = ''SDL2 Autogenerated wrapper'';
    inputs.flakeNimbleLib.type = "github";
  inputs.flakeNimbleLib.owner = "riinr";
  inputs.flakeNimbleLib.repo = "flake-nimble";
  inputs.flakeNimbleLib.ref = "flake-pinning";
  inputs.flakeNimbleLib.dir = "nimpkgs/";
  inputs.flakeNimbleLib.inputs.nixpkgs.follows = "nixpkgs";
  inputs.src-nim_sdl2-master.flake = false;
  inputs.src-nim_sdl2-master.type = "github";
  inputs.src-nim_sdl2-master.owner = "jyapayne";
  inputs.src-nim_sdl2-master.repo = "nim-sdl2";
  inputs.src-nim_sdl2-master.ref = "refs/heads/master";
  inputs.src-nim_sdl2-master.inputs.nixpkgs.follows = "nixpkgs";
  
  outputs = { self, nixpkgs, flakeNimbleLib, src-nim_sdl2-master, ...}@deps:
    let lib = flakeNimbleLib.lib;
    in lib.mkRefOutput {
      inherit self nixpkgs ;
      src = src-nim_sdl2-master;
      deps = builtins.removeAttrs deps ["self" "nixpkgs" "flakeNimbleLib" "src-nim_sdl2-master"];
      meta = builtins.fromJSON (builtins.readFile ./meta.json);
    };
}