{
  description = ''SDL2 Autogenerated wrapper'';
  inputs.src-nim_sdl2-master.flake = false;
  inputs.src-nim_sdl2-master.type = "github";
  inputs.src-nim_sdl2-master.owner = "jyapayne";
  inputs.src-nim_sdl2-master.repo = "nim-sdl2";
  inputs.src-nim_sdl2-master.ref = "refs/heads/master";
  
  outputs = { self, nixpkgs, src-nim_sdl2-master, ...}@deps:
    let lib = import ./lib.nix;
    in lib.mkRefOutput {
      inherit self nixpkgs ;
      src = src-nim_sdl2-master;
      deps = builtins.removeAttrs deps ["self" "nixpkgs" "src-nim_sdl2-master"];
      meta = builtins.fromJSON (builtins.readFile ./meta.json);
    };
}