{
  description = ''SDL2 Autogenerated wrapper'';
    inputs.flakeNimbleLib.type = "github";
  inputs.flakeNimbleLib.owner = "riinr";
  inputs.flakeNimbleLib.repo = "flake-nimble";
  inputs.flakeNimbleLib.ref = "flake-pinning";
  inputs.flakeNimbleLib.dir = "nimpkgs/";
  inputs.flakeNimbleLib.inputs.nixpkgs.follows = "nixpkgs";
    inputs."nim_sdl2-master".type = "github";
  inputs."nim_sdl2-master".owner = "riinr";
  inputs."nim_sdl2-master".repo = "flake-nimble";
  inputs."nim_sdl2-master".ref = "flake-pinning";
  inputs."nim_sdl2-master".dir = "nimpkgs/n/nim_sdl2/master";
  inputs."nim_sdl2-master".inputs.nixpkgs.follows = "nixpkgs";
  inputs."nim_sdl2-master".inputs.flakeNimbleLib.follows = "flakeNimbleLib";


  
  outputs = { self, nixpkgs, flakeNimbleLib, ...}@inputs:
    let lib = flakeNimbleLib.lib;
    in lib.mkProjectOutput {
      inherit self nixpkgs;
      refs = builtins.removeAttrs inputs ["self" "nixpkgs" "flakeNimbleLib"];
      meta = builtins.fromJSON (builtins.readFile ./meta.json);
    };
}