{
  description = ''
    SDL2 Autogenerated wrapper
  '';
  inputs.src-nim_sdl2.url = "https://github.com/jyapayne/nim-sdl2";
  outputs = inputs:
    let lib = import ../../nim-pkgs-drvs.nix;
    in lib.mkOutput {
      inherit inputs;
      meta = ./meta.json;
    };
}
