{
  description = ''
    Autogenerated glew bindings for Nim
  '';
  inputs.src-glew.url = "https://github.com/jyapayne/nim-glew";
  outputs = inputs:
    let lib = import ../../nim-pkgs-drvs.nix;
    in lib.mkOutput {
      inherit inputs;
      meta = ./meta.json;
    };
}
