[
{name="AntTweakBar";value=./AntTweakBar.json;}
{name="ArrayFireNim";value=./ArrayFireNim.json;}
{name="AstroNimy";value=./AstroNimy.json;}
{name="BN";value=./BN.json;}
{name="BipBuffer";value=./BipBuffer.json;}
{name="BitVector";value=./BitVector.json;}
{name="DevIL";value=./DevIL.json;}
{name="Kinto";value=./Kinto.json;}
{name="LLVM";value=./LLVM.json;}
{name="MiNiM";value=./MiNiM.json;}
{name="NiMPC";value=./NiMPC.json;}
{name="NimBorg";value=./NimBorg.json;}
{name="NimData";value=./NimData.json;}
{name="NimTacToe";value=./NimTacToe.json;}
{name="PPM";value=./PPM.json;}
{name="Phosphor";value=./Phosphor.json;}
{name="QuickJS4nim";value=./QuickJS4nim.json;}
{name="RC4";value=./RC4.json;}
{name="Remotery";value=./Remotery.json;}
{name="RingBuffer";value=./RingBuffer.json;}
{name="RollingHash";value=./RollingHash.json;}
{name="SDF";value=./SDF.json;}
{name="WebGL";value=./WebGL.json;}
{name="XPLM-Nim";value=./XPLM-Nim.json;}
{name="Xors3D";value=./Xors3D.json;}
{name="about";value=./about.json;}
{name="ad";value=./ad.json;}
{name="adb";value=./adb.json;}
{name="ajax";value=./ajax.json;}
{name="akane";value=./akane.json;}
{name="alea";value=./alea.json;}
{name="algebra";value=./algebra.json;}
{name="alignment";value=./alignment.json;}
{name="allegro5";value=./allegro5.json;}
{name="allographer";value=./allographer.json;}
{name="analytics";value=./analytics.json;}
{name="anime";value=./anime.json;}
{name="anonimongo";value=./anonimongo.json;}
{name="anybar";value=./anybar.json;}
{name="anycase";value=./anycase.json;}
{name="ao";value=./ao.json;}
{name="aporia";value=./aporia.json;}
{name="appdirs";value=./appdirs.json;}
{name="argon2";value=./argon2.json;}
{name="argon2_bind";value=./argon2_bind.json;}
{name="argparse";value=./argparse.json;}
{name="argument_parser";value=./argument_parser.json;}
{name="arksys";value=./arksys.json;}
{name="arraymancer";value=./arraymancer.json;}
{name="arraymancer_vision";value=./arraymancer_vision.json;}
{name="asciigraph";value=./asciigraph.json;}
{name="asciitables";value=./asciitables.json;}
{name="asciitype";value=./asciitype.json;}
{name="assimp";value=./assimp.json;}
{name="ast_pattern_matching";value=./ast_pattern_matching.json;}
{name="astar";value=./astar.json;}
{name="asyncdocker";value=./asyncdocker.json;}
{name="asyncevents";value=./asyncevents.json;}
{name="asyncmysql";value=./asyncmysql.json;}
{name="asyncpg";value=./asyncpg.json;}
{name="asyncpythonfile";value=./asyncpythonfile.json;}
{name="asynctools";value=./asynctools.json;}
{name="atoz";value=./atoz.json;}
{name="autome";value=./autome.json;}
{name="autotyper";value=./autotyper.json;}
{name="avbin";value=./avbin.json;}
{name="awesome_rmdir";value=./awesome_rmdir.json;}
{name="awk";value=./awk.json;}
{name="aws_sdk";value=./aws_sdk.json;}
{name="awslambda";value=./awslambda.json;}
{name="backoff";value=./backoff.json;}
{name="badgemaker";value=./badgemaker.json;}
{name="baker";value=./baker.json;}
{name="barbarus";value=./barbarus.json;}
{name="barcode";value=./barcode.json;}
{name="base32";value=./base32.json;}
{name="base58";value=./base58.json;}
{name="base62";value=./base62.json;}
{name="basedOn";value=./basedOn.json;}
{name="basic2d";value=./basic2d.json;}
{name="basic3d";value=./basic3d.json;}
{name="bcra";value=./bcra.json;}
{name="bcrypt";value=./bcrypt.json;}
{name="beanstalkd";value=./beanstalkd.json;}
{name="bearlibterminal";value=./bearlibterminal.json;}
{name="bearssl";value=./bearssl.json;}
{name="bencode";value=./bencode.json;}
{name="bgfx";value=./bgfx.json;}
{name="bgfxdotnim";value=./bgfxdotnim.json;}
{name="biblioteca_guarrilla";value=./biblioteca_guarrilla.json;}
{name="bigints";value=./bigints.json;}
{name="bignum";value=./bignum.json;}
{name="binance";value=./binance.json;}
{name="binaryheap";value=./binaryheap.json;}
{name="binaryparse";value=./binaryparse.json;}
{name="binio";value=./binio.json;}
{name="biscuits";value=./biscuits.json;}
{name="bitarray";value=./bitarray.json;}
{name="bitvec";value=./bitvec.json;}
{name="blake2";value=./blake2.json;}
{name="bloom";value=./bloom.json;}
{name="blosc";value=./blosc.json;}
{name="blscurve";value=./blscurve.json;}
{name="blurhash";value=./blurhash.json;}
{name="bluu";value=./bluu.json;}
{name="bncurve";value=./bncurve.json;}
{name="boneIO";value=./boneIO.json;}
{name="bped";value=./bped.json;}
{name="bpg";value=./bpg.json;}
{name="brainfuck";value=./brainfuck.json;}
{name="breeze";value=./breeze.json;}
{name="bson";value=./bson.json;}
{name="bump";value=./bump.json;}
{name="bytes2human";value=./bytes2human.json;}
{name="byteutils";value=./byteutils.json;}
{name="c2nim";value=./c2nim.json;}
{name="c4";value=./c4.json;}
{name="c_alikes";value=./c_alikes.json;}
{name="cache";value=./cache.json;}
{name="cairo";value=./cairo.json;}
{name="cal";value=./cal.json;}
{name="calibre";value=./calibre.json;}
{name="capnp";value=./capnp.json;}
{name="cascade";value=./cascade.json;}
{name="cassandra";value=./cassandra.json;}
{name="cassette";value=./cassette.json;}
{name="cbor";value=./cbor.json;}
{name="cello";value=./cello.json;}
{name="chebyshev";value=./chebyshev.json;}
{name="chipmunk6";value=./chipmunk6.json;}
{name="chipmunk7_demos";value=./chipmunk7_demos.json;}
{name="chonker";value=./chonker.json;}
{name="choosenim";value=./choosenim.json;}
{name="chroma";value=./chroma.json;}
{name="chronicles";value=./chronicles.json;}
{name="chrono";value=./chrono.json;}
{name="chronopipe";value=./chronopipe.json;}
{name="chronos";value=./chronos.json;}
{name="circleci_client";value=./circleci_client.json;}
{name="cirru-parser";value=./cirru-parser.json;}
{name="cittadino";value=./cittadino.json;}
{name="classy";value=./classy.json;}
{name="clblast";value=./clblast.json;}
{name="cli_menu";value=./cli_menu.json;}
{name="clibpp";value=./clibpp.json;}
{name="cligen";value=./cligen.json;}
{name="cliptomania";value=./cliptomania.json;}
{name="closure_compiler";value=./closure_compiler.json;}
{name="clr";value=./clr.json;}
{name="cmake";value=./cmake.json;}
{name="cmd";value=./cmd.json;}
{name="cmixer";value=./cmixer.json;}
{name="cmixer_sdl2";value=./cmixer_sdl2.json;}
{name="coalesce";value=./coalesce.json;}
{name="cobs";value=./cobs.json;}
{name="coco";value=./coco.json;}
{name="collections";value=./collections.json;}
{name="colorcol";value=./colorcol.json;}
{name="colorize";value=./colorize.json;}
{name="colorsys";value=./colorsys.json;}
{name="combparser";value=./combparser.json;}
{name="commandeer";value=./commandeer.json;}
{name="compactdict";value=./compactdict.json;}
{name="compiler";value=./compiler.json;}
{name="complex";value=./complex.json;}
{name="configparser";value=./configparser.json;}
{name="confutils";value=./confutils.json;}
{name="conio";value=./conio.json;}
{name="constants";value=./constants.json;}
{name="consul";value=./consul.json;}
{name="contra";value=./contra.json;}
{name="contracts";value=./contracts.json;}
{name="controlStructures";value=./controlStructures.json;}
{name="coverage";value=./coverage.json;}
{name="coverartarchive";value=./coverartarchive.json;}
{name="cppstl";value=./cppstl.json;}
{name="crap";value=./crap.json;}
{name="crc32";value=./crc32.json;}
{name="criterion";value=./criterion.json;}
{name="crosscompile";value=./crosscompile.json;}
{name="csfml";value=./csfml.json;}
{name="css_html_minify";value=./css_html_minify.json;}
{name="csv";value=./csv.json;}
{name="csvql";value=./csvql.json;}
{name="csvtable";value=./csvtable.json;}
{name="csvtools";value=./csvtools.json;}
{name="ctrulib";value=./ctrulib.json;}
{name="cucumber";value=./cucumber.json;}
{name="currying";value=./currying.json;}
{name="d3";value=./d3.json;}
{name="daemon";value=./daemon.json;}
{name="daemonim";value=./daemonim.json;}
{name="daemonize";value=./daemonize.json;}
{name="dali";value=./dali.json;}
{name="dashing";value=./dashing.json;}
{name="datetime2human";value=./datetime2human.json;}
{name="db";value=./db.json;}
{name="db_clickhouse";value=./db_clickhouse.json;}
{name="db_presto";value=./db_presto.json;}
{name="dbg";value=./dbg.json;}
{name="dbschema";value=./dbschema.json;}
{name="dbus";value=./dbus.json;}
{name="decisiontree";value=./decisiontree.json;}
{name="delaunay";value=./delaunay.json;}
{name="delight";value=./delight.json;}
{name="des";value=./des.json;}
{name="dialogs";value=./dialogs.json;}
{name="diff";value=./diff.json;}
{name="diffoutput";value=./diffoutput.json;}
{name="digitalocean";value=./digitalocean.json;}
{name="directnimrod";value=./directnimrod.json;}
{name="discordnim";value=./discordnim.json;}
{name="dnsclient";value=./dnsclient.json;}
{name="dnsprotec";value=./dnsprotec.json;}
{name="docopt";value=./docopt.json;}
{name="docx";value=./docx.json;}
{name="dotenv";value=./dotenv.json;}
{name="dpdk";value=./dpdk.json;}
{name="drand48";value=./drand48.json;}
{name="drawille";value=./drawille.json;}
{name="dropbox_filename_sanitizer";value=./dropbox_filename_sanitizer.json;}
{name="dtoa";value=./dtoa.json;}
{name="duktape";value=./duktape.json;}
{name="easings";value=./easings.json;}
{name="eastasianwidth";value=./eastasianwidth.json;}
{name="easy_bcrypt";value=./easy_bcrypt.json;}
{name="easymail";value=./easymail.json;}
{name="ed25519";value=./ed25519.json;}
{name="edens";value=./edens.json;}
{name="edn";value=./edn.json;}
{name="egl";value=./egl.json;}
{name="einheit";value=./einheit.json;}
{name="eloverblik";value=./eloverblik.json;}
{name="elvis";value=./elvis.json;}
{name="emerald";value=./emerald.json;}
{name="eminim";value=./eminim.json;}
{name="emmy";value=./emmy.json;}
{name="enet";value=./enet.json;}
{name="ensem";value=./ensem.json;}
{name="entoody";value=./entoody.json;}
{name="envconfig";value=./envconfig.json;}
{name="epub";value=./epub.json;}
{name="espeak";value=./espeak.json;}
{name="etcd_client";value=./etcd_client.json;}
{name="eternity";value=./eternity.json;}
{name="eth";value=./eth.json;}
{name="eth_bloom";value=./eth_bloom.json;}
{name="eth_common";value=./eth_common.json;}
{name="eth_keyfile";value=./eth_keyfile.json;}
{name="eth_keys";value=./eth_keys.json;}
{name="eth_p2p";value=./eth_p2p.json;}
{name="eth_trie";value=./eth_trie.json;}
{name="ethash";value=./ethash.json;}
{name="euclidean";value=./euclidean.json;}
{name="euphony";value=./euphony.json;}
{name="euwren";value=./euwren.json;}
{name="evmc";value=./evmc.json;}
{name="evmjit";value=./evmjit.json;}
{name="expat";value=./expat.json;}
{name="extensions";value=./extensions.json;}
{name="extmath";value=./extmath.json;}
{name="fab";value=./fab.json;}
{name="faker";value=./faker.json;}
{name="falas";value=./falas.json;}
{name="fancygl";value=./fancygl.json;}
{name="fastcgi";value=./fastcgi.json;}
{name="faststack";value=./faststack.json;}
{name="faststreams";value=./faststreams.json;}
{name="fasttext";value=./fasttext.json;}
{name="fastx_reader";value=./fastx_reader.json;}
{name="feednim";value=./feednim.json;}
{name="ffbookmarks";value=./ffbookmarks.json;}
{name="fftw3";value=./fftw3.json;}
{name="fidget";value=./fidget.json;}
{name="figures";value=./figures.json;}
{name="fileinput";value=./fileinput.json;}
{name="filesize";value=./filesize.json;}
{name="finals";value=./finals.json;}
{name="finalseg";value=./finalseg.json;}
{name="findtests";value=./findtests.json;}
{name="firejail";value=./firejail.json;}
{name="fixmath";value=./fixmath.json;}
{name="flatdb";value=./flatdb.json;}
{name="fletcher";value=./fletcher.json;}
{name="flippy";value=./flippy.json;}
{name="fltk";value=./fltk.json;}
{name="fmod";value=./fmod.json;}
{name="fnmatch";value=./fnmatch.json;}
{name="fnv";value=./fnv.json;}
{name="foliant";value=./foliant.json;}
{name="fontconfig";value=./fontconfig.json;}
{name="foreach";value=./foreach.json;}
{name="forestdb";value=./forestdb.json;}
{name="fowltek";value=./fowltek.json;}
{name="frag";value=./frag.json;}
{name="fragments";value=./fragments.json;}
{name="freegeoip";value=./freegeoip.json;}
{name="freeimage";value=./freeimage.json;}
{name="freetype";value=./freetype.json;}
{name="fsm";value=./fsm.json;}
{name="fsmonitor";value=./fsmonitor.json;}
{name="fswatch";value=./fswatch.json;}
{name="fugitive";value=./fugitive.json;}
{name="funchook";value=./funchook.json;}
{name="fuse";value=./fuse.json;}
{name="fwrite";value=./fwrite.json;}
{name="gamelib";value=./gamelib.json;}
{name="gamelight";value=./gamelight.json;}
{name="gameoflife";value=./gameoflife.json;}
{name="gapbuffer";value=./gapbuffer.json;}
{name="gara";value=./gara.json;}
{name="gatabase";value=./gatabase.json;}
{name="gcplat";value=./gcplat.json;}
{name="gdbmc";value=./gdbmc.json;}
{name="gen";value=./gen.json;}
{name="genieos";value=./genieos.json;}
{name="genode";value=./genode.json;}
{name="genoiser";value=./genoiser.json;}
{name="gentabs";value=./gentabs.json;}
{name="geocoding";value=./geocoding.json;}
{name="geohash";value=./geohash.json;}
{name="geoip";value=./geoip.json;}
{name="geonames";value=./geonames.json;}
{name="georefar";value=./georefar.json;}
{name="getch";value=./getch.json;}
{name="getmac";value=./getmac.json;}
{name="getr";value=./getr.json;}
{name="ggplotnim";value=./ggplotnim.json;}
{name="gh_nimrod_doc_pages";value=./gh_nimrod_doc_pages.json;}
{name="gifenc";value=./gifenc.json;}
{name="gifwriter";value=./gifwriter.json;}
{name="gimei";value=./gimei.json;}
{name="ginger";value=./ginger.json;}
{name="gintro";value=./gintro.json;}
{name="gitapi";value=./gitapi.json;}
{name="github";value=./github.json;}
{name="github_api";value=./github_api.json;}
{name="github_release";value=./github_release.json;}
{name="gles";value=./gles.json;}
{name="glfw";value=./glfw.json;}
{name="glm";value=./glm.json;}
{name="glob";value=./glob.json;}
{name="glossolalia";value=./glossolalia.json;}
{name="gmp";value=./gmp.json;}
{name="gnuplot";value=./gnuplot.json;}
{name="gnutls";value=./gnutls.json;}
{name="godot";value=./godot.json;}
{name="golden";value=./golden.json;}
{name="golib";value=./golib.json;}
{name="googleapi";value=./googleapi.json;}
{name="googlesearch";value=./googlesearch.json;}
{name="gplay";value=./gplay.json;}
{name="gpx";value=./gpx.json;}
{name="grafanim";value=./grafanim.json;}
{name="graphemes";value=./graphemes.json;}
{name="graphics";value=./graphics.json;}
{name="gravatar";value=./gravatar.json;}
{name="grim";value=./grim.json;}
{name="grp";value=./grp.json;}
{name="gtk2";value=./gtk2.json;}
{name="gtkgenui";value=./gtkgenui.json;}
{name="gungnir";value=./gungnir.json;}
{name="gurl";value=./gurl.json;}
{name="gyaric";value=./gyaric.json;}
{name="hackpad";value=./hackpad.json;}
{name="haraka";value=./haraka.json;}
{name="hashids";value=./hashids.json;}
{name="hastyscribe";value=./hastyscribe.json;}
{name="hex";value=./hex.json;}
{name="hmac";value=./hmac.json;}
{name="horde3d";value=./horde3d.json;}
{name="hpack";value=./hpack.json;}
{name="html5_canvas";value=./html5_canvas.json;}
{name="html_tools";value=./html_tools.json;}
{name="htmlview";value=./htmlview.json;}
{name="hts";value=./hts.json;}
{name="httpauth";value=./httpauth.json;}
{name="httpbeast";value=./httpbeast.json;}
{name="httpform";value=./httpform.json;}
{name="httpkit";value=./httpkit.json;}
{name="httputils";value=./httputils.json;}
{name="huenim";value=./huenim.json;}
{name="i18n";value=./i18n.json;}
{name="i3ipc";value=./i3ipc.json;}
{name="illwill";value=./illwill.json;}
{name="illwill_unsafe";value=./illwill_unsafe.json;}
{name="imageman";value=./imageman.json;}
{name="imap";value=./imap.json;}
{name="imghdr";value=./imghdr.json;}
{name="importc_helpers";value=./importc_helpers.json;}
{name="impulse_engine";value=./impulse_engine.json;}
{name="influx";value=./influx.json;}
{name="inim";value=./inim.json;}
{name="intel_hex";value=./intel_hex.json;}
{name="interfaced";value=./interfaced.json;}
{name="io-egl";value=./io-egl.json;}
{name="io-gles";value=./io-gles.json;}
{name="io-isense";value=./io-isense.json;}
{name="io-myo";value=./io-myo.json;}
{name="io-oculus";value=./io-oculus.json;}
{name="io-serialport";value=./io-serialport.json;}
{name="io-sixense";value=./io-sixense.json;}
{name="io-spacenav";value=./io-spacenav.json;}
{name="io-usb";value=./io-usb.json;}
{name="ipsumgenera";value=./ipsumgenera.json;}
{name="irc";value=./irc.json;}
{name="isa";value=./isa.json;}
{name="isaac";value=./isaac.json;}
{name="isense";value=./isense.json;}
{name="itchio";value=./itchio.json;}
{name="itertools";value=./itertools.json;}
{name="iterutils";value=./iterutils.json;}
{name="itn";value=./itn.json;}
{name="iup";value=./iup.json;}
{name="jack";value=./jack.json;}
{name="jade-nim";value=./jade-nim.json;}
{name="jdec";value=./jdec.json;}
{name="jester";value=./jester.json;}
{name="jnim";value=./jnim.json;}
{name="joyent_http_parser";value=./joyent_http_parser.json;}
{name="jsbind";value=./jsbind.json;}
{name="jscanvas";value=./jscanvas.json;}
{name="jser";value=./jser.json;}
{name="jsmn";value=./jsmn.json;}
{name="json_builder";value=./json_builder.json;}
{name="json_rpc";value=./json_rpc.json;}
{name="json_serialization";value=./json_serialization.json;}
{name="jsonob";value=./jsonob.json;}
{name="jsonschema";value=./jsonschema.json;}
{name="jstin";value=./jstin.json;}
{name="jsutils";value=./jsutils.json;}
{name="jswebsockets";value=./jswebsockets.json;}
{name="jwt";value=./jwt.json;}
{name="kaitai_struct_nim_runtime";value=./kaitai_struct_nim_runtime.json;}
{name="karax";value=./karax.json;}
{name="kdialog";value=./kdialog.json;}
{name="keccak_tiny";value=./keccak_tiny.json;}
{name="kexpr";value=./kexpr.json;}
{name="keyring";value=./keyring.json;}
{name="keystone";value=./keystone.json;}
{name="kissfft";value=./kissfft.json;}
{name="kiwi";value=./kiwi.json;}
{name="kmer";value=./kmer.json;}
{name="kmod";value=./kmod.json;}
{name="kslog";value=./kslog.json;}
{name="kview";value=./kview.json;}
{name="kwin";value=./kwin.json;}
{name="ladder";value=./ladder.json;}
{name="lapper";value=./lapper.json;}
{name="laser";value=./laser.json;}
{name="lastfm";value=./lastfm.json;}
{name="lazy";value=./lazy.json;}
{name="lazy_rest";value=./lazy_rest.json;}
{name="lc";value=./lc.json;}
{name="lda";value=./lda.json;}
{name="leveldb";value=./leveldb.json;}
{name="libarchibi";value=./libarchibi.json;}
{name="libbacktrace";value=./libbacktrace.json;}
{name="libclang";value=./libclang.json;}
{name="libcurl";value=./libcurl.json;}
{name="libevdev";value=./libevdev.json;}
{name="libffi";value=./libffi.json;}
{name="libfswatch";value=./libfswatch.json;}
{name="libgcrypt";value=./libgcrypt.json;}
{name="libgit2";value=./libgit2.json;}
{name="libgraph";value=./libgraph.json;}
{name="libipset";value=./libipset.json;}
{name="libjwt";value=./libjwt.json;}
{name="libkeepass";value=./libkeepass.json;}
{name="libmpdclient";value=./libmpdclient.json;}
{name="libnotify";value=./libnotify.json;}
{name="libnx";value=./libnx.json;}
{name="libovr";value=./libovr.json;}
{name="libp2p";value=./libp2p.json;}
{name="libplist";value=./libplist.json;}
{name="libravatar";value=./libravatar.json;}
{name="libsha";value=./libsha.json;}
{name="libsodium";value=./libsodium.json;}
{name="libssh";value=./libssh.json;}
{name="libssh2";value=./libssh2.json;}
{name="libsvm";value=./libsvm.json;}
{name="libsvm_legacy";value=./libsvm_legacy.json;}
{name="libtcod_nim";value=./libtcod_nim.json;}
{name="libu2f";value=./libu2f.json;}
{name="libusb";value=./libusb.json;}
{name="libuv";value=./libuv.json;}
{name="lilt";value=./lilt.json;}
{name="linalg";value=./linalg.json;}
{name="linenoise";value=./linenoise.json;}
{name="linuxfb";value=./linuxfb.json;}
{name="list_comprehension";value=./list_comprehension.json;}
{name="listsv";value=./listsv.json;}
{name="litestore";value=./litestore.json;}
{name="lmdb";value=./lmdb.json;}
{name="loadenv";value=./loadenv.json;}
{name="locale";value=./locale.json;}
{name="loco";value=./loco.json;}
{name="loki";value=./loki.json;}
{name="lolcat";value=./lolcat.json;}
{name="looper";value=./looper.json;}
{name="loopfusion";value=./loopfusion.json;}
{name="lq";value=./lq.json;}
{name="lscolors";value=./lscolors.json;}
{name="lua";value=./lua.json;}
{name="ludens";value=./ludens.json;}
{name="luhncheck";value=./luhncheck.json;}
{name="luhny";value=./luhny.json;}
{name="luna";value=./luna.json;}
{name="macroutils";value=./macroutils.json;}
{name="magic";value=./magic.json;}
{name="mangle";value=./mangle.json;}
{name="manu";value=./manu.json;}
{name="mapbits";value=./mapbits.json;}
{name="markdown";value=./markdown.json;}
{name="masterpassword";value=./masterpassword.json;}
{name="mathexpr";value=./mathexpr.json;}
{name="matplotnim";value=./matplotnim.json;}
{name="maybe";value=./maybe.json;}
{name="maze";value=./maze.json;}
{name="mcmurry";value=./mcmurry.json;}
{name="mddoc";value=./mddoc.json;}
{name="mdevolve";value=./mdevolve.json;}
{name="memo";value=./memo.json;}
{name="memviews";value=./memviews.json;}
{name="mentat";value=./mentat.json;}
{name="metar";value=./metar.json;}
{name="metatools";value=./metatools.json;}
{name="metric";value=./metric.json;}
{name="metrics";value=./metrics.json;}
{name="microasynchttpserver";value=./microasynchttpserver.json;}
{name="midnight_dynamite";value=./midnight_dynamite.json;}
{name="migrate";value=./migrate.json;}
{name="minhash";value=./minhash.json;}
{name="miniz";value=./miniz.json;}
{name="minmaxheap";value=./minmaxheap.json;}
{name="mmgeoip";value=./mmgeoip.json;}
{name="mnemonic";value=./mnemonic.json;}
{name="moduleinit";value=./moduleinit.json;}
{name="moe";value=./moe.json;}
{name="mofuw";value=./mofuw.json;}
{name="mongo";value=./mongo.json;}
{name="mongopool";value=./mongopool.json;}
{name="monit";value=./monit.json;}
{name="monocypher";value=./monocypher.json;}
{name="morelogging";value=./morelogging.json;}
{name="mort";value=./mort.json;}
{name="moustachu";value=./moustachu.json;}
{name="mpdclient";value=./mpdclient.json;}
{name="mpeg";value=./mpeg.json;}
{name="mpfit";value=./mpfit.json;}
{name="mpwc";value=./mpwc.json;}
{name="mqtt";value=./mqtt.json;}
{name="msgpack";value=./msgpack.json;}
{name="msgpack4nim";value=./msgpack4nim.json;}
{name="multicast";value=./multicast.json;}
{name="murmur";value=./murmur.json;}
{name="murmur3";value=./murmur3.json;}
{name="murmurhash";value=./murmurhash.json;}
{name="mustache";value=./mustache.json;}
{name="mutableseqs";value=./mutableseqs.json;}
{name="myo";value=./myo.json;}
{name="mysqlparser";value=./mysqlparser.json;}
{name="nake";value=./nake.json;}
{name="names";value=./names.json;}
{name="nanoid";value=./nanoid.json;}
{name="nanomsg";value=./nanomsg.json;}
{name="nanovg";value=./nanovg.json;}
{name="nanovg.nim";value=./nanovg.nim.json;}
{name="nap";value=./nap.json;}
{name="nasher";value=./nasher.json;}
{name="nat_traversal";value=./nat_traversal.json;}
{name="native_dialogs";value=./native_dialogs.json;}
{name="nbaser";value=./nbaser.json;}
{name="ncurses";value=./ncurses.json;}
{name="ndb";value=./ndb.json;}
{name="ndbex";value=./ndbex.json;}
{name="ndf";value=./ndf.json;}
{name="negamax";value=./negamax.json;}
{name="neo";value=./neo.json;}
{name="nerve";value=./nerve.json;}
{name="nesm";value=./nesm.json;}
{name="nest";value=./nest.json;}
{name="netpbm";value=./netpbm.json;}
{name="netpipe";value=./netpipe.json;}
{name="neverwinter";value=./neverwinter.json;}
{name="news";value=./news.json;}
{name="ngxcmod";value=./ngxcmod.json;}
{name="nhsl";value=./nhsl.json;}
{name="nico";value=./nico.json;}
{name="nicy";value=./nicy.json;}
{name="nifty";value=./nifty.json;}
{name="nigui";value=./nigui.json;}
{name="niledb";value=./niledb.json;}
{name="nim-libgd";value=./nim-libgd.json;}
{name="nim7z";value=./nim7z.json;}
{name="nimAES";value=./nimAES.json;}
{name="nimAGG";value=./nimAGG.json;}
{name="nimBMP";value=./nimBMP.json;}
{name="nimCEF";value=./nimCEF.json;}
{name="nimFinLib";value=./nimFinLib.json;}
{name="nimLUA";value=./nimLUA.json;}
{name="nimPDF";value=./nimPDF.json;}
{name="nimPNG";value=./nimPNG.json;}
{name="nimSHA2";value=./nimSHA2.json;}
{name="nim_cexc";value=./nim_cexc.json;}
{name="nim_cjson";value=./nim_cjson.json;}
{name="nim_curry";value=./nim_curry.json;}
{name="nim_exodus";value=./nim_exodus.json;}
{name="nim_miniz";value=./nim_miniz.json;}
{name="nim_telegram_bot";value=./nim_telegram_bot.json;}
{name="nim_tiled";value=./nim_tiled.json;}
{name="nimactors";value=./nimactors.json;}
{name="nimagehide";value=./nimagehide.json;}
{name="nimalpm";value=./nimalpm.json;}
{name="nimarchive";value=./nimarchive.json;}
{name="nimassets";value=./nimassets.json;}
{name="nimates";value=./nimates.json;}
{name="nimbass";value=./nimbass.json;}
{name="nimbench";value=./nimbench.json;}
{name="nimbigwig";value=./nimbigwig.json;}
{name="nimbioseq";value=./nimbioseq.json;}
{name="nimblas";value=./nimblas.json;}
{name="nimble";value=./nimble.json;}
{name="nimblegui";value=./nimblegui.json;}
{name="nimbler";value=./nimbler.json;}
{name="nimbluez";value=./nimbluez.json;}
{name="nimbomb";value=./nimbomb.json;}
{name="nimboost";value=./nimboost.json;}
{name="nimbox";value=./nimbox.json;}
{name="nimbpf";value=./nimbpf.json;}
{name="nimbug";value=./nimbug.json;}
{name="nimbus";value=./nimbus.json;}
{name="nimcat";value=./nimcat.json;}
{name="nimcb";value=./nimcb.json;}
{name="nimcdl";value=./nimcdl.json;}
{name="nimcfitsio";value=./nimcfitsio.json;}
{name="nimcl";value=./nimcl.json;}
{name="nimclipboard";value=./nimclipboard.json;}
{name="nimclutter";value=./nimclutter.json;}
{name="nimcr";value=./nimcr.json;}
{name="nimcrypto";value=./nimcrypto.json;}
{name="nimcuda";value=./nimcuda.json;}
{name="nimcx";value=./nimcx.json;}
{name="nimdeps";value=./nimdeps.json;}
{name="nimes";value=./nimes.json;}
{name="nimetry";value=./nimetry.json;}
{name="nimeverything";value=./nimeverything.json;}
{name="nimfastText";value=./nimfastText.json;}
{name="nimfm";value=./nimfm.json;}
{name="nimfp";value=./nimfp.json;}
{name="nimfuzz";value=./nimfuzz.json;}
{name="nimfuzzy";value=./nimfuzzy.json;}
{name="nimga";value=./nimga.json;}
{name="nimgame";value=./nimgame.json;}
{name="nimgame2";value=./nimgame2.json;}
{name="nimgen";value=./nimgen.json;}
{name="nimgit2";value=./nimgit2.json;}
{name="nimgl";value=./nimgl.json;}
{name="nimgraphql";value=./nimgraphql.json;}
{name="nimgraphviz";value=./nimgraphviz.json;}
{name="nimgui";value=./nimgui.json;}
{name="nimha";value=./nimha.json;}
{name="nimhdf5";value=./nimhdf5.json;}
{name="nimhq";value=./nimhq.json;}
{name="nimhttpd";value=./nimhttpd.json;}
{name="nimi3status";value=./nimi3status.json;}
{name="niminst";value=./niminst.json;}
{name="nimjson";value=./nimjson.json;}
{name="nimkerberos";value=./nimkerberos.json;}
{name="nimlapack";value=./nimlapack.json;}
{name="nimler";value=./nimler.json;}
{name="nimlevenshtein";value=./nimlevenshtein.json;}
{name="nimlibxlsxwriter";value=./nimlibxlsxwriter.json;}
{name="nimline";value=./nimline.json;}
{name="nimlist";value=./nimlist.json;}
{name="nimlsp";value=./nimlsp.json;}
{name="nimly";value=./nimly.json;}
{name="nimlz4";value=./nimlz4.json;}
{name="nimmm";value=./nimmm.json;}
{name="nimmonocypher";value=./nimmonocypher.json;}
{name="nimna";value=./nimna.json;}
{name="nimnoise";value=./nimnoise.json;}
{name="nimobserver";value=./nimobserver.json;}
{name="nimodpi";value=./nimodpi.json;}
{name="nimongo";value=./nimongo.json;}
{name="nimp5";value=./nimp5.json;}
{name="nimpb";value=./nimpb.json;}
{name="nimpb_protoc";value=./nimpb_protoc.json;}
{name="nimpcre";value=./nimpcre.json;}
{name="nimpmda";value=./nimpmda.json;}
{name="nimpress";value=./nimpress.json;}
{name="nimpy";value=./nimpy.json;}
{name="nimqml";value=./nimqml.json;}
{name="nimquery";value=./nimquery.json;}
{name="nimr";value=./nimr.json;}
{name="nimrat";value=./nimrat.json;}
{name="nimrax";value=./nimrax.json;}
{name="nimrdkafka";value=./nimrdkafka.json;}
{name="nimrod-glfw";value=./nimrod-glfw.json;}
{name="nimroutine";value=./nimroutine.json;}
{name="nimrpc";value=./nimrpc.json;}
{name="nimrpc_milis";value=./nimrpc_milis.json;}
{name="nimrtlsdr";value=./nimrtlsdr.json;}
{name="nimrun";value=./nimrun.json;}
{name="nimshell";value=./nimshell.json;}
{name="nimsl";value=./nimsl.json;}
{name="nimsnappy";value=./nimsnappy.json;}
{name="nimsnappyc";value=./nimsnappyc.json;}
{name="nimspice";value=./nimspice.json;}
{name="nimssh2";value=./nimssh2.json;}
{name="nimssl";value=./nimssl.json;}
{name="nimstopwatch";value=./nimstopwatch.json;}
{name="nimsuggest";value=./nimsuggest.json;}
{name="nimsuite";value=./nimsuite.json;}
{name="nimsvg";value=./nimsvg.json;}
{name="nimterlingua";value=./nimterlingua.json;}
{name="nimterop";value=./nimterop.json;}
{name="nimtess2";value=./nimtess2.json;}
{name="nimtomd";value=./nimtomd.json;}
{name="nimwc";value=./nimwc.json;}
{name="nimwebp";value=./nimwebp.json;}
{name="nimx";value=./nimx.json;}
{name="nimzbar";value=./nimzbar.json;}
{name="nimzend";value=./nimzend.json;}
{name="nio";value=./nio.json;}
{name="nish";value=./nish.json;}
{name="niup";value=./niup.json;}
{name="nlopt";value=./nlopt.json;}
{name="nmiline";value=./nmiline.json;}
{name="nmqtt";value=./nmqtt.json;}
{name="noaa";value=./noaa.json;}
{name="node";value=./node.json;}
{name="noise";value=./noise.json;}
{name="nominatim";value=./nominatim.json;}
{name="nordnet";value=./nordnet.json;}
{name="norm";value=./norm.json;}
{name="normalize";value=./normalize.json;}
{name="norman";value=./norman.json;}
{name="notetxt";value=./notetxt.json;}
{name="notifications";value=./notifications.json;}
{name="notify";value=./notify.json;}
{name="notmuch";value=./notmuch.json;}
{name="npeg";value=./npeg.json;}
{name="npg";value=./npg.json;}
{name="nre";value=./nre.json;}
{name="nregex";value=./nregex.json;}
{name="nrpl";value=./nrpl.json;}
{name="nsh";value=./nsh.json;}
{name="nshout";value=./nshout.json;}
{name="nsu";value=./nsu.json;}
{name="ntangle";value=./ntangle.json;}
{name="number_files";value=./number_files.json;}
{name="numericalnim";value=./numericalnim.json;}
{name="nuuid";value=./nuuid.json;}
{name="nwt";value=./nwt.json;}
{name="oaitools";value=./oaitools.json;}
{name="oauth";value=./oauth.json;}
{name="oculus";value=./oculus.json;}
{name="oldgtk3";value=./oldgtk3.json;}
{name="oldwinapi";value=./oldwinapi.json;}
{name="omnilog";value=./omnilog.json;}
{name="onedrive";value=./onedrive.json;}
{name="oop_utils";value=./oop_utils.json;}
{name="open_elevation";value=./open_elevation.json;}
{name="openal";value=./openal.json;}
{name="openapi";value=./openapi.json;}
{name="opencl";value=./opencl.json;}
{name="opencv";value=./opencv.json;}
{name="openexchangerates";value=./openexchangerates.json;}
{name="opengl";value=./opengl.json;}
{name="openssl_evp";value=./openssl_evp.json;}
{name="openstreetmap";value=./openstreetmap.json;}
{name="openweathermap";value=./openweathermap.json;}
{name="optional_t";value=./optional_t.json;}
{name="optionals";value=./optionals.json;}
{name="options";value=./options.json;}
{name="optionsutils";value=./optionsutils.json;}
{name="orient";value=./orient.json;}
{name="ormin";value=./ormin.json;}
{name="os_files";value=./os_files.json;}
{name="osdialog";value=./osdialog.json;}
{name="osinfo";value=./osinfo.json;}
{name="osrm";value=./osrm.json;}
{name="osureplay";value=./osureplay.json;}
{name="osutil";value=./osutil.json;}
{name="otp";value=./otp.json;}
{name="overpass";value=./overpass.json;}
{name="owo";value=./owo.json;}
{name="p4ztag_to_json";value=./p4ztag_to_json.json;}
{name="package_visible_types";value=./package_visible_types.json;}
{name="packedjson";value=./packedjson.json;}
{name="pager";value=./pager.json;}
{name="paranim";value=./paranim.json;}
{name="pararules";value=./pararules.json;}
{name="paratext";value=./paratext.json;}
{name="paravim";value=./paravim.json;}
{name="pari";value=./pari.json;}
{name="parseFixed";value=./parseFixed.json;}
{name="parseini";value=./parseini.json;}
{name="parsetoml";value=./parsetoml.json;}
{name="pas2nim";value=./pas2nim.json;}
{name="passgen";value=./passgen.json;}
{name="pastebin";value=./pastebin.json;}
{name="patgraph";value=./patgraph.json;}
{name="patty";value=./patty.json;}
{name="pcap";value=./pcap.json;}
{name="pcgbasic";value=./pcgbasic.json;}
{name="pdcurses";value=./pdcurses.json;}
{name="perlin";value=./perlin.json;}
{name="persistent_enums";value=./persistent_enums.json;}
{name="persvector";value=./persvector.json;}
{name="pfring";value=./pfring.json;}
{name="pg";value=./pg.json;}
{name="pg_util";value=./pg_util.json;}
{name="phoon";value=./phoon.json;}
{name="physfs";value=./physfs.json;}
{name="picohttpparser";value=./picohttpparser.json;}
{name="pine";value=./pine.json;}
{name="pinggraph";value=./pinggraph.json;}
{name="pipe";value=./pipe.json;}
{name="pipelines";value=./pipelines.json;}
{name="platformer";value=./platformer.json;}
{name="playground";value=./playground.json;}
{name="playlists";value=./playlists.json;}
{name="pledge";value=./pledge.json;}
{name="plists";value=./plists.json;}
{name="plotly";value=./plotly.json;}
{name="pluginmanager";value=./pluginmanager.json;}
{name="plugins";value=./plugins.json;}
{name="plz";value=./plz.json;}
{name="png";value=./png.json;}
{name="pnm";value=./pnm.json;}
{name="polyBool";value=./polyBool.json;}
{name="polynumeric";value=./polynumeric.json;}
{name="polypbren";value=./polypbren.json;}
{name="pomTimer";value=./pomTimer.json;}
{name="pop3";value=./pop3.json;}
{name="porter";value=./porter.json;}
{name="primme";value=./primme.json;}
{name="print";value=./print.json;}
{name="printdebug";value=./printdebug.json;}
{name="procs";value=./procs.json;}
{name="progress";value=./progress.json;}
{name="prologue";value=./prologue.json;}
{name="prometheus";value=./prometheus.json;}
{name="prompt";value=./prompt.json;}
{name="protobuf";value=./protobuf.json;}
{name="protocoled";value=./protocoled.json;}
{name="proton";value=./proton.json;}
{name="proxyproto";value=./proxyproto.json;}
{name="psutil";value=./psutil.json;}
{name="ptest";value=./ptest.json;}
{name="ptrace";value=./ptrace.json;}
{name="pudge";value=./pudge.json;}
{name="pvim";value=./pvim.json;}
{name="pwd";value=./pwd.json;}
{name="pwned";value=./pwned.json;}
{name="pych";value=./pych.json;}
{name="pykot";value=./pykot.json;}
{name="pylib";value=./pylib.json;}
{name="pymod";value=./pymod.json;}
{name="python";value=./python.json;}
{name="python3";value=./python3.json;}
{name="pythonfile";value=./pythonfile.json;}
{name="pythonize";value=./pythonize.json;}
{name="pythonmath";value=./pythonmath.json;}
{name="pythonpathlib";value=./pythonpathlib.json;}
{name="q";value=./q.json;}
{name="qr";value=./qr.json;}
{name="qrcode";value=./qrcode.json;}
{name="qrcodegen";value=./qrcodegen.json;}
{name="qt5_qtsql";value=./qt5_qtsql.json;}
{name="quadtree";value=./quadtree.json;}
{name="quickjwt";value=./quickjwt.json;}
{name="rain";value=./rain.json;}
{name="rainbow";value=./rainbow.json;}
{name="random";value=./random.json;}
{name="random_font_color";value=./random_font_color.json;}
{name="randpw";value=./randpw.json;}
{name="ranges";value=./ranges.json;}
{name="rapid";value=./rapid.json;}
{name="rbac";value=./rbac.json;}
{name="rbtree";value=./rbtree.json;}
{name="rdgui";value=./rdgui.json;}
{name="react";value=./react.json;}
{name="react16";value=./react16.json;}
{name="reactor";value=./reactor.json;}
{name="reactorfuse";value=./reactorfuse.json;}
{name="readfq";value=./readfq.json;}
{name="recaptcha";value=./recaptcha.json;}
{name="rect";value=./rect.json;}
{name="rect_packer";value=./rect_packer.json;}
{name="redis";value=./redis.json;}
{name="redisclient";value=./redisclient.json;}
{name="redisparser";value=./redisparser.json;}
{name="redissessions";value=./redissessions.json;}
{name="redneck_translator";value=./redneck_translator.json;}
{name="redpool";value=./redpool.json;}
{name="redux";value=./redux.json;}
{name="redux_nim";value=./redux_nim.json;}
{name="reframe";value=./reframe.json;}
{name="regex";value=./regex.json;}
{name="remarker_light";value=./remarker_light.json;}
{name="replim";value=./replim.json;}
{name="requirementstxt";value=./requirementstxt.json;}
{name="result";value=./result.json;}
{name="rethinkdb";value=./rethinkdb.json;}
{name="retranslator";value=./retranslator.json;}
{name="rexpaint";value=./rexpaint.json;}
{name="rfc3339";value=./rfc3339.json;}
{name="ringDeque";value=./ringDeque.json;}
{name="ris";value=./ris.json;}
{name="rlp";value=./rlp.json;}
{name="robotparser";value=./robotparser.json;}
{name="rocksdb";value=./rocksdb.json;}
{name="rodcli";value=./rodcli.json;}
{name="romans";value=./romans.json;}
{name="roots";value=./roots.json;}
{name="rosencrantz";value=./rosencrantz.json;}
{name="rss";value=./rss.json;}
{name="rsvg";value=./rsvg.json;}
{name="rtree";value=./rtree.json;}
{name="sam";value=./sam.json;}
{name="samson";value=./samson.json;}
{name="sass";value=./sass.json;}
{name="saya";value=./saya.json;}
{name="scgi";value=./scgi.json;}
{name="schedules";value=./schedules.json;}
{name="science";value=./science.json;}
{name="scnim";value=./scnim.json;}
{name="scram";value=./scram.json;}
{name="sctp";value=./sctp.json;}
{name="sdl1";value=./sdl1.json;}
{name="sdl2";value=./sdl2.json;}
{name="sdl2_nim";value=./sdl2_nim.json;}
{name="sdnotify";value=./sdnotify.json;}
{name="seccomp";value=./seccomp.json;}
{name="secp256k1";value=./secp256k1.json;}
{name="sections";value=./sections.json;}
{name="segmentation";value=./segmentation.json;}
{name="semver";value=./semver.json;}
{name="seqmath";value=./seqmath.json;}
{name="sequester";value=./sequester.json;}
{name="sequoia";value=./sequoia.json;}
{name="sequtils2";value=./sequtils2.json;}
{name="serial";value=./serial.json;}
{name="serialization";value=./serialization.json;}
{name="serializetools";value=./serializetools.json;}
{name="serialport";value=./serialport.json;}
{name="seriesdetiempoar";value=./seriesdetiempoar.json;}
{name="sermon";value=./sermon.json;}
{name="sfml";value=./sfml.json;}
{name="sha1";value=./sha1.json;}
{name="sha1ext";value=./sha1ext.json;}
{name="sha3";value=./sha3.json;}
{name="shaname";value=./shaname.json;}
{name="shared";value=./shared.json;}
{name="sharedmempool";value=./sharedmempool.json;}
{name="shell";value=./shell.json;}
{name="shimsham";value=./shimsham.json;}
{name="shiori";value=./shiori.json;}
{name="shiori_charset_convert";value=./shiori_charset_convert.json;}
{name="shioridll";value=./shioridll.json;}
{name="shizuka";value=./shizuka.json;}
{name="shlex";value=./shlex.json;}
{name="shoco";value=./shoco.json;}
{name="shorturl";value=./shorturl.json;}
{name="signals";value=./signals.json;}
{name="sigv4";value=./sigv4.json;}
{name="sim";value=./sim.json;}
{name="simdX86";value=./simdX86.json;}
{name="simhash";value=./simhash.json;}
{name="simpleAST";value=./simpleAST.json;}
{name="simple_graph";value=./simple_graph.json;}
{name="simple_parseopt";value=./simple_parseopt.json;}
{name="simple_vector";value=./simple_vector.json;}
{name="simpledecimal";value=./simpledecimal.json;}
{name="simplediff";value=./simplediff.json;}
{name="simpleot";value=./simpleot.json;}
{name="simplepng";value=./simplepng.json;}
{name="siphash";value=./siphash.json;}
{name="sitmo";value=./sitmo.json;}
{name="sixense";value=./sixense.json;}
{name="skEasing";value=./skEasing.json;}
{name="skbintext";value=./skbintext.json;}
{name="ski";value=./ski.json;}
{name="skinterpolate";value=./skinterpolate.json;}
{name="sksbox";value=./sksbox.json;}
{name="skybook";value=./skybook.json;}
{name="skyhash";value=./skyhash.json;}
{name="slacklib";value=./slacklib.json;}
{name="slimdown";value=./slimdown.json;}
{name="sling";value=./sling.json;}
{name="smnar";value=./smnar.json;}
{name="snail";value=./snail.json;}
{name="snappy";value=./snappy.json;}
{name="sndfile";value=./sndfile.json;}
{name="sndhdr";value=./sndhdr.json;}
{name="snip";value=./snip.json;}
{name="socks";value=./socks.json;}
{name="sodium";value=./sodium.json;}
{name="sol";value=./sol.json;}
{name="sonic";value=./sonic.json;}
{name="sophia";value=./sophia.json;}
{name="sorta";value=./sorta.json;}
{name="sound";value=./sound.json;}
{name="soundio";value=./soundio.json;}
{name="spacenav";value=./spacenav.json;}
{name="sparkline";value=./sparkline.json;}
{name="spdk";value=./spdk.json;}
{name="spdx_licenses";value=./spdx_licenses.json;}
{name="sph";value=./sph.json;}
{name="sphincs";value=./sphincs.json;}
{name="sphinx";value=./sphinx.json;}
{name="spills";value=./spills.json;}
{name="spinny";value=./spinny.json;}
{name="spotify";value=./spotify.json;}
{name="spry";value=./spry.json;}
{name="sprymicro";value=./sprymicro.json;}
{name="spryvm";value=./spryvm.json;}
{name="spurdify";value=./spurdify.json;}
{name="spwd";value=./spwd.json;}
{name="sqlbuilder";value=./sqlbuilder.json;}
{name="sqlite3_abi";value=./sqlite3_abi.json;}
{name="srt";value=./srt.json;}
{name="srv";value=./srv.json;}
{name="sss";value=./sss.json;}
{name="stacks";value=./stacks.json;}
{name="staticglfw";value=./staticglfw.json;}
{name="statsd_client";value=./statsd_client.json;}
{name="stb_image";value=./stb_image.json;}
{name="std_shims";value=./std_shims.json;}
{name="steam";value=./steam.json;}
{name="steamworks";value=./steamworks.json;}
{name="steganography";value=./steganography.json;}
{name="stew";value=./stew.json;}
{name="stint";value=./stint.json;}
{name="stones";value=./stones.json;}
{name="stopwatch";value=./stopwatch.json;}
{name="stor";value=./stor.json;}
{name="stringinterpolation";value=./stringinterpolation.json;}
{name="strslice";value=./strslice.json;}
{name="struct";value=./struct.json;}
{name="strunicode";value=./strunicode.json;}
{name="subexes";value=./subexes.json;}
{name="subfield";value=./subfield.json;}
{name="subhook";value=./subhook.json;}
{name="subviewer";value=./subviewer.json;}
{name="suffer";value=./suffer.json;}
{name="sugerror";value=./sugerror.json;}
{name="suggest";value=./suggest.json;}
{name="sunvox";value=./sunvox.json;}
{name="svdpi";value=./svdpi.json;}
{name="svgo";value=./svgo.json;}
{name="swayipc";value=./swayipc.json;}
{name="sweetanitify";value=./sweetanitify.json;}
{name="switch_build";value=./switch_build.json;}
{name="synthesis";value=./synthesis.json;}
{name="syphus";value=./syphus.json;}
{name="syscall";value=./syscall.json;}
{name="sysinfo";value=./sysinfo.json;}
{name="syslog";value=./syslog.json;}
{name="sysrandom";value=./sysrandom.json;}
{name="systimes";value=./systimes.json;}
{name="taglib";value=./taglib.json;}
{name="taps";value=./taps.json;}
{name="tcl";value=./tcl.json;}
{name="tcping";value=./tcping.json;}
{name="teafiles";value=./teafiles.json;}
{name="telebot";value=./telebot.json;}
{name="tempdir";value=./tempdir.json;}
{name="tempfile";value=./tempfile.json;}
{name="templates";value=./templates.json;}
{name="termbox";value=./termbox.json;}
{name="terminaltables";value=./terminaltables.json;}
{name="termnovel";value=./termnovel.json;}
{name="termstyle";value=./termstyle.json;}
{name="testify";value=./testify.json;}
{name="testrunner";value=./testrunner.json;}
{name="testutils";value=./testutils.json;}
{name="texttospeech";value=./texttospeech.json;}
{name="tf2plug";value=./tf2plug.json;}
{name="the_nim_alliance";value=./the_nim_alliance.json;}
{name="tiger";value=./tiger.json;}
{name="timecop";value=./timecop.json;}
{name="timeit";value=./timeit.json;}
{name="timerpool";value=./timerpool.json;}
{name="timespec_get";value=./timespec_get.json;}
{name="timezones";value=./timezones.json;}
{name="tinamou";value=./tinamou.json;}
{name="tiny_sqlite";value=./tiny_sqlite.json;}
{name="tinyfiledialogs";value=./tinyfiledialogs.json;}
{name="tissue";value=./tissue.json;}
{name="tnim";value=./tnim.json;}
{name="tor";value=./tor.json;}
{name="torch";value=./torch.json;}
{name="toxcore";value=./toxcore.json;}
{name="translation";value=./translation.json;}
{name="treesitter";value=./treesitter.json;}
{name="treesitter_agda";value=./treesitter_agda.json;}
{name="treesitter_bash";value=./treesitter_bash.json;}
{name="treesitter_c";value=./treesitter_c.json;}
{name="treesitter_c_sharp";value=./treesitter_c_sharp.json;}
{name="treesitter_cpp";value=./treesitter_cpp.json;}
{name="treesitter_css";value=./treesitter_css.json;}
{name="treesitter_go";value=./treesitter_go.json;}
{name="treesitter_haskell";value=./treesitter_haskell.json;}
{name="treesitter_html";value=./treesitter_html.json;}
{name="treesitter_java";value=./treesitter_java.json;}
{name="treesitter_javascript";value=./treesitter_javascript.json;}
{name="treesitter_ocaml";value=./treesitter_ocaml.json;}
{name="treesitter_php";value=./treesitter_php.json;}
{name="treesitter_python";value=./treesitter_python.json;}
{name="treesitter_ruby";value=./treesitter_ruby.json;}
{name="treesitter_rust";value=./treesitter_rust.json;}
{name="treesitter_scala";value=./treesitter_scala.json;}
{name="treesitter_typescript";value=./treesitter_typescript.json;}
{name="triplets";value=./triplets.json;}
{name="tsundoku";value=./tsundoku.json;}
{name="tsv2json";value=./tsv2json.json;}
{name="ttmath";value=./ttmath.json;}
{name="tuples";value=./tuples.json;}
{name="turn_based_game";value=./turn_based_game.json;}
{name="twitter";value=./twitter.json;}
{name="typelists";value=./typelists.json;}
{name="typography";value=./typography.json;}
{name="ui";value=./ui.json;}
{name="uibuilder";value=./uibuilder.json;}
{name="ulid";value=./ulid.json;}
{name="unicode_numbers";value=./unicode_numbers.json;}
{name="unicodedb";value=./unicodedb.json;}
{name="unicodeplus";value=./unicodeplus.json;}
{name="units";value=./units.json;}
{name="unpack";value=./unpack.json;}
{name="unsplash";value=./unsplash.json;}
{name="untar";value=./untar.json;}
{name="ur";value=./ur.json;}
{name="urand";value=./urand.json;}
{name="uri2";value=./uri2.json;}
{name="uri3";value=./uri3.json;}
{name="urlshortener";value=./urlshortener.json;}
{name="usagov";value=./usagov.json;}
{name="useragents";value=./useragents.json;}
{name="usha";value=./usha.json;}
{name="usigar";value=./usigar.json;}
{name="ustring";value=./ustring.json;}
{name="utils";value=./utils.json;}
{name="uuid";value=./uuid.json;}
{name="uuids";value=./uuids.json;}
{name="validateip";value=./validateip.json;}
{name="validation";value=./validation.json;}
{name="validator";value=./validator.json;}
{name="values";value=./values.json;}
{name="variant";value=./variant.json;}
{name="variantkey";value=./variantkey.json;}
{name="vec";value=./vec.json;}
{name="vecio";value=./vecio.json;}
{name="vecmath";value=./vecmath.json;}
{name="vectors";value=./vectors.json;}
{name="vidhdr";value=./vidhdr.json;}
{name="vkapi";value=./vkapi.json;}
{name="vla";value=./vla.json;}
{name="vmath";value=./vmath.json;}
{name="vmvc";value=./vmvc.json;}
{name="wChart";value=./wChart.json;}
{name="wNim";value=./wNim.json;}
{name="wZeeGrid";value=./wZeeGrid.json;}
{name="wave";value=./wave.json;}
{name="weave";value=./weave.json;}
{name="web3";value=./web3.json;}
{name="webaudio";value=./webaudio.json;}
{name="webdavclient";value=./webdavclient.json;}
{name="webdriver";value=./webdriver.json;}
{name="webp";value=./webp.json;}
{name="websocket";value=./websocket.json;}
{name="webterminal";value=./webterminal.json;}
{name="webview";value=./webview.json;}
{name="weightedgraph";value=./weightedgraph.json;}
{name="whip";value=./whip.json;}
{name="wiki2text";value=./wiki2text.json;}
{name="wings";value=./wings.json;}
{name="winim";value=./winim.json;}
{name="winregistry";value=./winregistry.json;}
{name="winserial";value=./winserial.json;}
{name="winversion";value=./winversion.json;}
{name="wiringPiNim";value=./wiringPiNim.json;}
{name="witai";value=./witai.json;}
{name="with";value=./with.json;}
{name="woocommerce-api-nim";value=./woocommerce-api-nim.json;}
{name="word2vec";value=./word2vec.json;}
{name="wox";value=./wox.json;}
{name="wren";value=./wren.json;}
{name="ws";value=./ws.json;}
{name="wstp";value=./wstp.json;}
{name="x11";value=./x11.json;}
{name="xcm";value=./xcm.json;}
{name="xdo";value=./xdo.json;}
{name="xiaomi";value=./xiaomi.json;}
{name="xlsx";value=./xlsx.json;}
{name="xml";value=./xml.json;}
{name="xmldom";value=./xmldom.json;}
{name="xmldomparser";value=./xmldomparser.json;}
{name="xmltools";value=./xmltools.json;}
{name="xxhash";value=./xxhash.json;}
{name="xxtea";value=./xxtea.json;}
{name="yahooweather";value=./yahooweather.json;}
{name="yaml";value=./yaml.json;}
{name="yukiko";value=./yukiko.json;}
{name="z3";value=./z3.json;}
{name="z3nim";value=./z3nim.json;}
{name="zero_functional";value=./zero_functional.json;}
{name="zfblast";value=./zfblast.json;}
{name="zfcore";value=./zfcore.json;}
{name="zhsh";value=./zhsh.json;}
{name="zip";value=./zip.json;}
{name="zmq";value=./zmq.json;}
]
